VERSION_MAJOR = 0
VERSION_MINOR = 5
VERSION_PATCH = 0

VERSION_TUPLE = (VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH)

VERSION = "{major}.{minor}.{patch}".format(
    major=VERSION_MAJOR, minor=VERSION_MINOR, patch=VERSION_PATCH
)
